---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
library(mypaintr)
knitr::knit_hooks$set(mypaint = knitr_mypaint_hook())

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.ext = "png",
  fig.width = 5,
  fig.keep = "none",
  mypaint = TRUE,
  fig.path = "man/figures/README-"
)
```

# mypaintr

<!-- badges: start -->
<!-- badges: end -->

mypaintr is an R package that lets you plot graphics in a human-like, sketched
way, using brushes from the [libmypaint](https://github.com/mypaint/libmypaint)
library and algorithms for "rough" lines and polygons.


Installation:

``` r
# install.packages("pak")
pak::pak("hughjonesd/mypaintr")
```

A base R barplot using a custom brush, plus a hand-drawn axis:

```{r, mypaint=TRUE, fig.keep="none"}
library(mypaintr)

# on the command line, do: 
# mypaint_device("output.png")

set_brush("tanda/acrylic-05-paint")
barplot(VADeaths, axes = FALSE, 
        beside = TRUE, col = palette.colors(5), border = NA,
        cex.names = 0.8)

set_brush(NULL)
set_hand(hand(wobble = 0))
axis(side = 2, at = seq(0, 60, 20))

# dev.off()
```

A ggplot using a custom element:

```{r, mypaint=TRUE, fig.keep="none"}
library(ggplot2)

ggplot(diamonds) +
  mypaint_wrap(
    geom_bar(aes(cut, fill = cut)),
    brush = "experimental/bubble"
  ) +
  theme_minimal() 

# ggsave("output.png", device = mypaint_device)
```

Sketchy lines using the ordinary base R device:

```{r, mypaint=FALSE, fig.keep="high"}

plot(1:10, 1:10, type = "n", xlab = "", ylab = "", axes = FALSE)

draw_rough_polygons(5 + 3 * sin(2*pi * 1:5/5), 5 + 3 * cos(2*pi * 1:5/5),
                    border = "darkred", col = "red3", lwd = 2,
                    hand = human_hand(seed = 1, multi_stroke = 3),
                    fill_pattern = crosshatch())

draw_rough_arrows(8, 8.5, 5.5, 5.5, lwd = 2, 
                  hand = human_hand(seed = 1, bow = 0.05))
text(8, 9, "A pentagon", family = "Chalkboard")
```

