name: pkgdown

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends libcairo2-dev libjson-c-dev libcurl4-openssl-dev libssl-dev libxml2-dev rsync

      - name: Install extra dependencies
        run: |
          apt-get install -y --no-install-recommends libmypaint-1.5-1 libmypaint-dev mypaint-brushes

      - name: Install R dependencies
        run: |
          install.packages(c("pkgdown", "knitr", "rmarkdown", "roxygen2", "ggplot2"))
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL --configure-args='--with-brushes=vendored' .

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
